version: '3'

services:
  frontend:
    build: ./frontendbank
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

